services:

  payment-app:
    build:
      context: ./paymentAndNotificationService
    container_name: payment-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./paymentAndNotificationService:/var/www/html
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - event-tickets-app
    command: ["sh", "/var/www/html/entrypoint.sh"]

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - event-tickets-app

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event-tickets-db
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - event-tickets-app

networks:
  event-tickets-app:

volumes:
  mysql_data:
